#!/bin/sh
# avoid being interrupted by child or keyboard
trap : INT QUIT TSTP

# Default runlevel. The runlevels used by PLD are:
#   0 - halt (Do NOT set initdefault to this)
#   1 - Single user mode
#   2 - Multiuser, without NFS (The same as 3, if you do not have networking)
#   3 - Full multiuser mode
#   4 - unused
#   5 - X11
#   6 - reboot (Do NOT set initdefault to this)

set -x
echo "args: $#:$@"
runlevel="$1"
case "$runlevel" in
3)
	exec /sbin/initng --i_am_init &
	echo "initng execution failed!"
;;
0|6)
	/sbin/ngc -j halt
;;
esac
